site_name: Cogitate Data Release

theme:
    name: readthedocs
    logo: https://github.com/Cogitate-consortium/cogitate-data/raw/merge_docs/assets/documentation/graphics/cogitate_logo.png
    palette:
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
        # Palette toggle for light mode
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
    extra_css:
        - site/css/theme_extra.css
    extra:
        generator: false
