site_name: Cogitate Data Release

theme:
    name: readthedocs
    logo: https://github.com/Cogitate-consortium/cogitate-data/blob/main/assets/documentation_v1.0/graphics_v1.0/cogitate_logo.png
    custom_dir: site
    palette:
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
        # Palette toggle for light mode
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
    extra_css:
        - css/extra.css
    extra:
        generator: false